services:
  - type: web
    name: taskflow-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_P3sDibBZXkq9@ep-spring-dew-ao47gwdp.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "20"
